packages:
  - 'packages/**'
  - '!**/test/**'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.20-alpha.4
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.20-alpha.4
  vite-plus: 0.1.20-alpha.4
overrides:
  '@docsearch/js>preact': 10.29.0
  lodash: 4.17.23
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
