packages:
  - 'packages/**'
  - '!**/test/**'
catalog:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1633
  vitest: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-test@1633
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@1633
overrides:
  '@docsearch/js>preact': 10.29.0
  lodash: 4.17.23
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
